=== supunt/test_app/Peercore.DataService/SQL/Schema/SqlStructureValidator.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Table">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Columns">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Column" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="key" type="xs:string" use="required" />
            <xs:attribute name="type" type="tableType" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="Query">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Generic">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="commandType" use="required" type="sqlType"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Ingres">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="commandType" type="sqlType" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="SqlServer">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="commandType" type="sqlType" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Oracle">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="commandType" type="sqlType" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="sqlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Text"/>
      <xs:enumeration value="StoredProcedure"/>
      <xs:enumeration value="Table"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tableType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Primary"/>
      <xs:enumeration value="Secondary"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== supunt/test_app/Peercore.DataService/SQL/OrderSQL.xml
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/SqlStructureValidator.xsd">


  <Query id="GetNextSorderNo">
    <Generic commandType="Text">
      SELECT IFNULL(MAX(sorder_no),0)+1  FROM sorder_header
    </Generic>
    <Ingres commandType="Text">
      SELECT IFNULL(MAX(sorder_no),0)+1  FROM sorder_header
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
   
  </Query>

  <Query id="InsertSorderHeader">
    <Generic commandType="Text">
      INSERT INTO sorder_header
      (
      sorder_no,
      cust_code,
      order_date,
      ordered_by,
      order_type,
      date_required,
      cust_order_no,
      assignee_no,
      source_code,
      source_no,
      rep_code
      )
      
      VALUES
      (
      @SorderNo,
      @CustomerCode,
      @OrderDate,
      @OrderedBy,
      @OrderType,
      @DateRequired,
      @CustomerOrderNo,
      @AssigneeNo,
      @SourceCode,
      @SourceNo,
      @RepCode
      )
    </Generic>
    <Ingres commandType="Text">
      INSERT INTO sorder_header
      (
      sorder_no,
      cust_code,
      order_date,
      ordered_by,
      order_type,
      date_required,
      cust_order_no,
      assignee_no,
      source_code,
      source_no,
      rep_code
      )

      VALUES
      (
      @SorderNo,
      @CustomerCode,
      @OrderDate,
      @OrderedBy,
      @OrderType,
      @DateRequired,
      @CustomerOrderNo,
      @AssigneeNo,
      @SourceCode,
      @SourceNo,
      @RepCode
      )
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
    <SqlLight commandType="Text">
    </SqlLight>
  </Query>


  <Query id="InsertSorderDetail">
    <Generic commandType="Text">
      INSERT INTO sorder_detail
      (
      sorder_no,
      item_no,
      catlog_code,
      source_code,
      source_no,
      order_qty,
      desp_qty,
      pallet_qty,
      price,
      amount,
      disc_type,
      disc_percent,
      net_amount
      )

      VALUES
      (
      @SorderNo,
      @ItemNo,
      @CatlogCode,
      @SourceCode,
      @SourceNo,
      @OrderQty,
      @DespQty,
      @PalletQty,
      @Price,
      @Amount,
      @DiscType,
      @DiscPercent,
      @NetAmount
      )
    </Generic>
    <Ingres commandType="Text">
      INSERT INTO sorder_detail
      (
      sorder_no,
      item_no,
      catlog_code,
      source_code,
      source_no,
      order_qty,
      desp_qty,
      pallet_qty,
      price,
      amount,
      disc_type,
      disc_percent,
      net_amount
      )

      VALUES
      (
      @SorderNo,
      @ItemNo,
      @CatlogCode,
      @SourceCode,
      @SourceNo,
      @OrderQty,
      @DespQty,
      @PalletQty,
      @Price,
      @Amount,
      @DiscType,
      @DiscPercent,
      @NetAmount
      )
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
    <SqlLight commandType="Text">
    </SqlLight>
  </Query>

  <Query id="InsertOrderConfirmation">
    <Generic commandType="Text">
      INSERT INTO order_confirmation
      (
      order_confirmation_id,
      web_id,
      signature,
      latitude,
      longitude
      )

      VALUES
      (
      @OrderConfirmationId,
      @WebId,
      @Signature,
      @Latitude,
      @Longitude
      )
    </Generic>
    <Ingres commandType="Text">
      INSERT INTO order_confirmation
      (
      order_confirmation_id,
      web_id,
      signature,
      latitude,
      longitude
      )
      VALUES
      (
      @OrderConfirmationId,
      @WebId,
      @Signature,
      @Latitude,
      @Longitude
      )
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
    <SqlLight commandType="Text">
    </SqlLight>
  </Query>

  <Query id="GetNextOrderConfirmationId"> 
    <Generic commandType="Text">
      SELECT IFNULL(MAX(order_confirmation_id),0)+1  FROM order_confirmation
    </Generic>
    <Ingres commandType="Text">
      SELECT IFNULL(MAX(order_confirmation_id),0)+1  FROM order_confirmation
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>

  </Query>

  <Query id="GetNextPFDWebOrderId">
    <Generic commandType="Text">
      SELECT MAX(ID) FROM pfd_web_sorder_seq
    </Generic>
    <Ingres commandType="Text">
      SELECT MAX(ID) FROM pfd_web_sorder_seq
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>

  </Query>
  
  <Query id="IncrementCurrentPFDWebOrderID">
    <Generic commandType="Text">
      UPDATE pfd_web_sorder_seq SET ID = (ID + 1)
    </Generic>
    <Ingres commandType="Text">
      UPDATE pfd_web_sorder_seq SET ID = (ID + 1)
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>

  </Query>
  
  <Query id="InsertWebOrderHeader">
    <Generic commandType="Text">
      Insert Into web_sorder_header
      (
      web_id,
      order_date,
      date_required,
      cust_code,
      comments,
      order_note,
      purchase_code,
      status,
      is_acknowledgement_required,
      assignee_no,
      freight,
      is_saved,
      is_processed_by_web_svr,
      detail_changes_status,
      sender_edi,
      receiver_edi,
      msg_ref,
      response_date,
      initial_date_required,
      buyer_order_no,
      promotional_deal_no,
      buying_add_gs1_cd,
      shipping_add_gs1_cd,
      supplier_add_gs1_cd,
      order_tot_amt,
      tot_no_of_items,
      as2_identifier
      )
      Values
      (
      @WebId,
      @OrderDate,
      @DateRequired,
      @CustomerCode,
      @Comments,
      @OrderNote,
      @PurchaseCode,
      @Status,
      @IsAckReq,
      @AssigneeNo,
      @Freight,
      @IsSaved,
      @IsProcessed,
      @DetailStatus,
      @SenderAddress,
      @ReceiverAddress,
      @MsgRef,
      @OrderDate,
      @DateRequired,
      @BuyerOrderNo,
      @PromotionNo,
      @BuyingAddress,
      @ShippingAddress,
      @SupplierAddress,
      @TotalAmount,
      @ItemCount,
      @AS2Identifier
      )
    </Generic>
    <Ingres commandType="Text">
      Insert Into web_sorder_header
      (
      web_id,
      order_date,
      date_required,
      cust_code,
      comments,
      order_note,
      purchase_code,
      status,
      is_acknowledgement_required,
      assignee_no,
      freight,
      is_saved,
      is_processed_by_web_svr,
      detail_changes_status,
      sender_edi,
      receiver_edi,
      msg_ref,
      response_date,
      initial_date_required,
      buyer_order_no,
      promotional_deal_no,
      buying_add_gs1_cd,
      shipping_add_gs1_cd,
      supplier_add_gs1_cd,
      order_tot_amt,
      tot_no_of_items,
      as2_identifier
      )
      Values
      (
      @WebId,
      @OrderDate,
      @DateRequired,
      @CustomerCode,
      @Comments,
      @OrderNote,
      @PurchaseCode,
      @Status,
      @IsAckReq,
      @AssigneeNo,
      @Freight,
      @IsSaved,
      @IsProcessed,
      @DetailStatus,
      @SenderAddress,
      @ReceiverAddress,
      @MsgRef,
      @OrderDate,
      @DateRequired,
      @BuyerOrderNo,
      @PromotionNo,
      @BuyingAddress,
      @ShippingAddress,
      @SupplierAddress,
      @TotalAmount,
      @ItemCount,
      @AS2Identifier
      )
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
    <SqlLight commandType="Text">
    </SqlLight>
  </Query>

  <Query id="InsertWebOrderDetail">
    <Generic commandType="Text">
      Insert Into web_sorder_detail
      (
      web_id,
      catlog_code,
      order_qty,
      back_order_qty,
      unit_price,
      unit_cost,
      unit_discount_perc,
      tax,
      free_qty,
      product_note,
      record_status,
      gtin_code,
      initial_order_qty,
      initial_unit_price
      )
      Values
      (
      @WebId,
      @CatlogCode,
      @OrderQty,
      @BackOrderQty,
      @UnitPrice,
      @UnitCost,
      @UnitDiscountPerc,
      @Tax,
      @FreeQty,
      @ProductNote,
      @ItemStatus,
      @GTINCode,
      @OrderQty,
      @UnitPrice
      )
    </Generic>
    <Ingres commandType="Text">
      Insert Into web_sorder_detail
      (
      web_id,
      catlog_code,
      order_qty,
      back_order_qty,
      unit_price,
      unit_cost,
      unit_discount_perc,
      tax,
      free_qty,
      product_note,
      record_status,
      gtin_code,
      initial_order_qty,
      initial_unit_price
      )
      Values
      (
      @WebId,
      @CatlogCode,
      @OrderQty,
      @BackOrderQty,
      @UnitPrice,
      @UnitCost,
      @UnitDiscountPerc,
      @Tax,
      @FreeQty,
      @ProductNote,
      @ItemStatus,
      @GTINCode,
      @OrderQty,
      @UnitPrice
      )
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
    <SqlLight commandType="Text">
    </SqlLight>
  </Query>

  <Query id="CancelWebOrder">
    <Generic commandType="Text">
      UPDATE web_sorder_header
      SET Status='Delete'
      WHERE web_id=@OrderId
    </Generic>
    <Ingres commandType="Text">
      UPDATE web_sorder_header
      SET Status='Delete'
      WHERE web_id=@OrderId
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
    <SqlLight commandType="Text">
    </SqlLight>
  </Query>
  
  <Query id="GetWebOrderStatus">
    <Generic commandType="Text">
      SELECT Status
      FROM web_sorder_header
      WHERE web_id=@OrderId
    </Generic>
    <Ingres commandType="Text">
      SELECT Status
      FROM web_sorder_header
      WHERE web_id=@OrderId
    </Ingres>
    <SqlServer commandType="Text"></SqlServer>
    <Oracle commandType="Text"></Oracle>
    <SqlLight commandType="Text">
    </SqlLight>
  </Query>

  <Query id="GetWebOrders">
